server:
  port: 8080

spring:
  application:
    name: fcm_auth

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: msa
    url: jdbc:mysql://localhost:3304/fcm_auth

  jpa:
    hibernate:
      #      naming:
      #        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${REST_API_KEY}
            redirect-uri: ${REDIRECT_URI:http://localhost:8080/login/callback/kakao}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  key: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRE:3600000}
    header: Authorization
  refresh:
    expiration: ${JWT_REFRESH_EXPIRE:86400000}
    header: Authorization-refresh

